# Generated by Django 5.0.1 on 2025-06-26 05:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikelblog',
            options={'verbose_name_plural': '2. Artikel Blog'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. Kategori'},
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artikel.kategori'),
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='konten',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Belum ada konten', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
